name: coody_common_flutter
description: Coody common library for Flutter
version: 1.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.5

dependencies:
  bloc_concurrency: ^0.2.2
  cached_network_image: ^3.3.0
  file_picker: ^6.1.1
  firebase_analytics: ^10.7.1
  firebase_dynamic_links: ^5.4.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.9
  intl: ^0.18.1
  json_annotation: ^4.8.1
  jwt_decoder: ^2.0.1
  material_symbols_icons: ^4.2711.0
  package_info_plus: ^5.0.1
  photo_view: ^0.14.0
  rxdart: ^0.27.7
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  store_redirect: ^2.0.1
  table_calendar: ^3.0.9
  uni_links: ^0.5.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
